import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../../services/api";

export default function JobDetails() {
  const { id } = useLocalSearchParams(); const [job, setJob] = useState(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const result = await api.get("/jobs"); const found = (Array.isArray(result.data) ? result.data : []).find((item) => String(item.id) === String(id)); if (found) setJob(found); else setError("This job is no longer available."); } catch { setError("Could not load this job."); } }, [id]); useEffect(() => { load(); }, [load]);
  if (!job && !error) return <View style={styles.center}><ActivityIndicator size="large" color="#2563eb"/></View>;
  if (error) return <View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={() => router.back()} style={styles.backButton}><Text style={styles.backText}>Back to jobs</Text></Pressable></View>;
  const apply = () => { const url = job.applyLink || job.apply_link; if (url) Linking.openURL(job.application_method === "email" ? `mailto:${url}` : url).catch(() => {}); else router.push("/login"); };
  const save = async () => { const userId = await AsyncStorage.getItem("userId"); if (!userId) return router.push("/login"); try { await api.post("/save-job", { user_id: userId, job_id: job.id, source: "internal", title: job.title, company: job.company, location: job.location }); alert("Job saved successfully."); } catch { alert("Could not save this job. Please try again."); } };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>← Back to jobs</Text></Pressable><Text style={styles.title}>{job.title}</Text><Text style={styles.company}>{job.company}</Text><Text style={styles.location}>⌖ {job.location || "Location not specified"}</Text><View style={styles.facts}><Text style={styles.fact}>Salary: {job.salary || "Not disclosed"}</Text><Text style={styles.fact}>Experience: {job.experience || "Not specified"}</Text><Text style={styles.fact}>Type: {job.type || "Full-time"}</Text><Text style={styles.fact}>Mode: {job.mode || "Onsite"}</Text></View><Text style={styles.heading}>Job description</Text><Text style={styles.description}>{job.description || "No description provided."}</Text>{job.skills ? <><Text style={styles.heading}>Skills</Text><Text style={styles.description}>{job.skills}</Text></> : null}<Pressable onPress={apply} style={styles.apply}><Text style={styles.applyText}>{job.applyLink || job.apply_link ? "Apply on official job page" : "Login to apply"}</Text></Pressable><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>♡ Save this job</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:"#f4f7fb"},content:{padding:20,paddingBottom:44},back:{color:"#2563eb",fontWeight:"800"},title:{color:"#172033",fontSize:28,lineHeight:35,fontWeight:"900",marginTop:24},company:{color:"#2563eb",fontSize:18,fontWeight:"800",marginTop:9},location:{color:"#64748b",marginTop:7},facts:{gap:9,marginTop:24,backgroundColor:"#fff",borderRadius:16,padding:16},fact:{color:"#334155",fontSize:14},heading:{color:"#172033",fontSize:19,fontWeight:"900",marginTop:27},description:{color:"#526176",fontSize:14,lineHeight:22,marginTop:9},apply:{backgroundColor:"#2563eb",borderRadius:13,padding:16,marginTop:30,alignItems:"center"},applyText:{color:"#fff",fontWeight:"900",fontSize:15},save:{borderWidth:1,borderColor:"#fda4af",borderRadius:13,padding:15,marginTop:11,alignItems:"center",backgroundColor:"#fff"},saveText:{color:"#e11d48",fontWeight:"900",fontSize:15},center:{flex:1,backgroundColor:"#f4f7fb",alignItems:"center",justifyContent:"center",padding:24},error:{color:"#475569",fontWeight:"700",fontSize:16,textAlign:"center"},backButton:{marginTop:18,borderRadius:10,backgroundColor:"#2563eb",paddingHorizontal:18,paddingVertical:12},backText:{color:"#fff",fontWeight:"800"} });
