import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";
import BottomNav from "../components/BottomNav";

export default function Applications() {
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [signedIn,setSignedIn]=useState(false);
  const load=useCallback(async()=>{const token=await AsyncStorage.getItem("token");setSignedIn(Boolean(token));if(!token){setLoading(false);return;}try{const response=await api.get("/applications",{headers:{Authorization:`Bearer ${token}`}});setItems(Array.isArray(response.data)?response.data:[]);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" color="#2563eb"/></View>;
  if(!signedIn)return <SafeAreaView style={styles.screen}><View style={styles.center}><Text style={styles.emptyTitle}>Log in to view applications</Text><Pressable onPress={()=>router.replace("/login")} style={styles.primary}><Text style={styles.primaryText}>Log in</Text></Pressable></View><BottomNav active="applications" /></SafeAreaView>;
  return <SafeAreaView style={styles.screen}><View style={styles.header}><Pressable onPress={()=>router.replace("/home")}><Text style={styles.back}>← Home</Text></Pressable><Text style={styles.heading}>Applications</Text><Text style={styles.sub}>Tap an application to view updates and requested documents.</Text></View><FlatList data={items} keyExtractor={(item)=>String(item.id)} contentContainerStyle={styles.list} renderItem={({item})=><Pressable onPress={()=>router.push({pathname:"/application-workspace",params:{id:String(item.id)}})} style={styles.card}><View style={styles.mark}><Text style={styles.markText}>{String(item.company||"M").charAt(0).toUpperCase()}</Text></View><View style={styles.info}><Text style={styles.title}>{item.title||"Job application"}</Text><Text style={styles.company}>{item.company||"MarketLence Jobs"}</Text><Text style={styles.location}>⌖ {item.location||"Location not specified"}</Text><Text style={styles.status}>{String(item.status||"Applied").replace(/_/g," ")}</Text></View><Text style={styles.arrow}>›</Text></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No applications yet</Text><Text style={styles.emptyText}>Your submitted applications will appear here.</Text><Pressable onPress={()=>router.replace("/home")} style={styles.primary}><Text style={styles.primaryText}>Explore jobs</Text></Pressable></View>}/><BottomNav active="applications" /></SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},header:{padding:20,paddingBottom:9},back:{color:"#2563eb",fontWeight:"800"},heading:{fontSize:28,fontWeight:"900",color:"#172033",marginTop:17},sub:{color:"#64748b",fontSize:12,lineHeight:18,marginTop:5},list:{padding:16,paddingTop:8,paddingBottom:32},card:{backgroundColor:"#fff",borderRadius:17,padding:15,flexDirection:"row",alignItems:"center",marginBottom:11,borderWidth:1,borderColor:"#e5eaf2"},mark:{width:46,height:46,borderRadius:15,backgroundColor:"#e0ecff",alignItems:"center",justifyContent:"center"},markText:{fontSize:19,fontWeight:"900",color:"#2563eb"},info:{marginLeft:12,flex:1},title:{fontSize:16,fontWeight:"900",color:"#172033"},company:{color:"#2563eb",fontSize:12,fontWeight:"700",marginTop:3},location:{color:"#64748b",fontSize:11,marginTop:4},status:{alignSelf:"flex-start",color:"#15803d",backgroundColor:"#dcfce7",borderRadius:10,paddingHorizontal:8,paddingVertical:4,marginTop:8,fontSize:10,fontWeight:"900",textTransform:"capitalize"},arrow:{fontSize:28,color:"#2563eb"},center:{flex:1,alignItems:"center",justifyContent:"center",padding:28,backgroundColor:"#f4f7fb"},empty:{alignItems:"center",paddingTop:70,paddingHorizontal:27},emptyTitle:{fontSize:20,fontWeight:"900",color:"#172033",textAlign:"center"},emptyText:{color:"#64748b",lineHeight:20,textAlign:"center",marginTop:8},primary:{backgroundColor:"#2563eb",paddingHorizontal:20,paddingVertical:12,borderRadius:12,marginTop:20},primaryText:{color:"#fff",fontWeight:"900"}});
