import AsyncStorage from "@react-native-async-storage/async-storage";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, FlatList, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import BottomNav from "../components/BottomNav";
import api from "../services/api";
export default function Applications() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [loggedIn, setLoggedIn] = useState(false);
  const load = async () => { setLoading(true); const token = await AsyncStorage.getItem("token"); setLoggedIn(Boolean(token)); if (!token) { setLoading(false); return; } try { setItems((await api.get("/applications")).data || []); } catch { setItems([]); } finally { setLoading(false); } };
  useFocusEffect(useCallback(() => { load(); }, []));
  return <SafeAreaView style={styles.safe}><View style={styles.heading}><Text style={styles.title}>Applications</Text><Text style={styles.sub}>Follow every application in one place.</Text></View>{loading ? <ActivityIndicator style={styles.loader} color="#2563EB" size="large" /> : !loggedIn ? <Empty text="Log in to track your applications." action="Log in" /> : <FlatList data={items} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Empty text="No applications yet. Start exploring roles today." action="Browse jobs" />} renderItem={({item}) => <View style={styles.card}><View style={styles.row}><Text style={styles.job}>{item.title}</Text><Text style={styles.status}>{item.status || "Submitted"}</Text></View><Text style={styles.company}>{item.company}</Text><Text style={styles.date}>Applied {new Date(item.created_at).toLocaleDateString()}</Text></View>} /> }<BottomNav /></SafeAreaView>;
}
function Empty({text,action}) { return <View style={styles.empty}><Text style={styles.emptyText}>{text}</Text><TouchableOpacity style={styles.primary} onPress={() => router.replace(action === "Log in" ? "/login" : "/home")}><Text style={styles.primaryText}>{action}</Text></TouchableOpacity></View>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F8FF"},heading:{padding:20,paddingBottom:8},title:{fontSize:27,fontWeight:"800",color:"#111827"},sub:{marginTop:5,color:"#64748B"},loader:{flex:1},list:{padding:20,paddingTop:12,paddingBottom:30,flexGrow:1},card:{backgroundColor:"#FFF",borderRadius:17,padding:18,marginBottom:12,borderWidth:1,borderColor:"#E5EAF3"},row:{flexDirection:"row",gap:8},job:{flex:1,fontSize:17,fontWeight:"800",color:"#111827"},status:{color:"#1D4ED8",backgroundColor:"#DBEAFE",paddingHorizontal:9,paddingVertical:4,borderRadius:20,fontSize:11,fontWeight:"800",alignSelf:"flex-start"},company:{color:"#475569",marginTop:6,fontWeight:"600"},date:{color:"#64748B",marginTop:12,fontSize:13},empty:{flex:1,alignItems:"center",justifyContent:"center",padding:30},emptyText:{color:"#475569",fontSize:16,textAlign:"center",lineHeight:23},primary:{backgroundColor:"#2563EB",borderRadius:12,paddingHorizontal:20,paddingVertical:13,marginTop:18},primaryText:{color:"#FFF",fontWeight:"800"}});
