import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import * as DocumentPicker from "expo-document-picker";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";

export default function ApplicationWorkspace(){
 const {id}=useLocalSearchParams();const [data,setData]=useState(null),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(""),[message,setMessage]=useState(""),[sending,setSending]=useState(false);
 const load=useCallback(async()=>{try{const token=await AsyncStorage.getItem("token");const r=await api.get(`/applications/${id}/workspace`,{headers:{Authorization:`Bearer ${token}`}});setData(r.data);}catch(e){Alert.alert("Could not load application",e?.response?.data?.error||"Please try again.");}finally{setLoading(false);}},[id]);useEffect(()=>{load();},[load]);
 const upload=async(r)=>{const pick=await DocumentPicker.getDocumentAsync({type:["application/pdf","image/*","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],copyToCacheDirectory:true});if(pick.canceled)return;const a=pick.assets[0];setUploading(String(r.id));try{const token=await AsyncStorage.getItem("token"),form=new FormData();form.append("document",{uri:a.uri,name:a.name,type:a.mimeType||"application/octet-stream"});await api.post(`/applications/${id}/documents/${r.id}`,form,{headers:{Authorization:`Bearer ${token}`,"Content-Type":"multipart/form-data"}});Alert.alert("Document uploaded");load();}catch(e){Alert.alert("Upload failed",e?.response?.data?.error||"Try another document.");}finally{setUploading("");}};
 const send=async()=>{if(!message.trim())return;setSending(true);try{const token=await AsyncStorage.getItem("token");await api.post(`/applications/${id}/messages`,{body:message.trim()},{headers:{Authorization:`Bearer ${token}`}});setMessage("");load();}catch(e){Alert.alert("Message failed",e?.response?.data?.error||"Please try again.");}finally{setSending(false);}};
 if(loading)return <View style={s.center}><ActivityIndicator size="large" color="#2563eb"/></View>;const app=data?.application||{},docs=data?.documents||[],messages=data?.messages||[];
 return <SafeAreaView style={s.screen}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Back</Text></Pressable><Text style={s.heading}>Application workspace</Text><Text style={s.title}>{app.title||"Your application"}</Text><Text style={s.company}>{app.company||"MarketLence Jobs"}</Text></View><ScrollView contentContainerStyle={s.content}><Text style={s.section}>Status</Text><Text style={s.status}>{app.status||"Applied"}</Text><Text style={s.section}>Requested documents</Text>{docs.length?docs.map(d=><View key={d.id} style={s.card}><View style={{flex:1}}><Text style={s.bold}>{d.document_name}</Text><Text style={s.small}>{d.note||"Requested by employer"}</Text><Text style={s.request}>{d.status==="uploaded"?"Uploaded":"Action required"}</Text></View>{d.status!=="uploaded"?<Pressable onPress={()=>upload(d)} style={s.button}>{uploading===String(d.id)?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Upload</Text>}</Pressable>:<Text style={s.done}>✓</Text>}</View>):<Text style={s.small}>No documents requested.</Text>}<Text style={s.section}>Messages</Text>{messages.length?messages.map(m=><View key={m.id} style={[s.message,m.sender_role==="candidate"&&s.mine]}><Text style={s.messageRole}>{m.sender_role==="candidate"?"You":"Employer"}</Text><Text style={s.messageText}>{m.body}</Text></View>):<Text style={s.small}>No messages yet.</Text>}<View style={s.composer}><TextInput value={message} onChangeText={setMessage} placeholder="Write a message" placeholderTextColor="#94a3b8" style={s.input} multiline/><Pressable onPress={send} disabled={sending} style={s.send}>{sending?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Send</Text>}</Pressable></View><Text style={s.section}>History</Text>{(data?.history||[]).map((h,i)=><View key={i} style={s.history}><Text style={s.bold}>{h.status}</Text><Text style={s.small}>{h.note||"Status updated"}</Text></View>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},header:{padding:20,backgroundColor:"#fff"},back:{color:"#2563eb",fontWeight:"800"},heading:{fontSize:25,fontWeight:"900",color:"#172033",marginTop:18},title:{fontSize:16,color:"#172033",fontWeight:"900",marginTop:12},company:{color:"#2563eb",fontSize:13,fontWeight:"700",marginTop:3},content:{padding:16,paddingBottom:40},section:{fontSize:17,fontWeight:"900",color:"#172033",marginTop:17,marginBottom:9},status:{alignSelf:"flex-start",backgroundColor:"#dcfce7",color:"#15803d",borderRadius:15,padding:9,fontWeight:"900"},card:{backgroundColor:"#fff",borderRadius:15,padding:14,marginBottom:9,flexDirection:"row",alignItems:"center"},bold:{color:"#172033",fontWeight:"900"},small:{color:"#64748b",fontSize:12,lineHeight:18,marginTop:4},request:{color:"#e11d48",fontWeight:"800",fontSize:11,marginTop:7},button:{backgroundColor:"#2563eb",paddingHorizontal:12,paddingVertical:10,borderRadius:10,minWidth:68,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"900",fontSize:12},done:{fontSize:23,color:"#16a34a",marginLeft:10},message:{backgroundColor:"#fff",padding:12,borderRadius:13,marginBottom:8},mine:{backgroundColor:"#dbeafe"},messageRole:{color:"#2563eb",fontSize:10,fontWeight:"900"},messageText:{color:"#172033",lineHeight:19,marginTop:4},composer:{marginTop:8,flexDirection:"row",gap:8,alignItems:"flex-end"},input:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:"#d8e0eb",borderRadius:12,padding:11,minHeight:46,maxHeight:110,color:"#172033"},send:{backgroundColor:"#2563eb",borderRadius:11,padding:13,minWidth:57,alignItems:"center"},history:{borderLeftWidth:3,borderLeftColor:"#2563eb",paddingLeft:10,paddingVertical:5,marginBottom:5},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#f4f7fb"}});
