import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import * as DocumentPicker from "expo-document-picker";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";

export default function ApplicationWorkspace() {
  const { id } = useLocalSearchParams(); const [data,setData] = useState(null); const [loading,setLoading] = useState(true); const [uploading,setUploading] = useState("");
  const load = useCallback(async () => { try { const token = await AsyncStorage.getItem("token"); const response = await api.get(`/applications/${id}/workspace`, {headers:{Authorization:`Bearer ${token}`}}); setData(response.data); } catch (error) { Alert.alert("Could not load application", error?.response?.data?.error || "Please try again."); } finally { setLoading(false); } }, [id]);
  useEffect(()=>{load();},[load]);
  const upload = async (request) => { const result = await DocumentPicker.getDocumentAsync({type:["application/pdf","image/*","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],copyToCacheDirectory:true}); if (result.canceled) return; const asset = result.assets[0]; setUploading(String(request.id)); try { const token=await AsyncStorage.getItem("token"); const form=new FormData(); form.append("document",{uri:asset.uri,name:asset.name,type:asset.mimeType||"application/octet-stream"}); await api.post(`/applications/${id}/documents/${request.id}`,form,{headers:{Authorization:`Bearer ${token}`,"Content-Type":"multipart/form-data"}}); Alert.alert("Document uploaded", "The employer can now review your document."); load(); } catch (error) { Alert.alert("Upload failed",error?.response?.data?.error || "Please choose a PDF, image, or Word document and try again."); } finally { setUploading(""); } };
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" color="#2563eb"/></View>;
  const app=data?.application||{}; const documents=Array.isArray(data?.documents)?data.documents:[];
  return <SafeAreaView style={styles.screen}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.heading}>Application workspace</Text><Text style={styles.title}>{app.title||"Your application"}</Text><Text style={styles.company}>{app.company||"MarketLence Jobs"}</Text></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.section}>Current status</Text><View style={styles.status}><Text style={styles.statusText}>{app.status||"Applied"}</Text></View><Text style={styles.section}>Requested documents</Text>{documents.length?documents.map((request)=><View key={request.id} style={styles.request}><View style={{flex:1}}><Text style={styles.requestTitle}>{request.document_name}</Text>{request.note?<Text style={styles.note}>{request.note}</Text>:null}<Text style={styles.requestStatus}>{request.status === "uploaded" ? "Uploaded" : "Action required"}</Text></View>{request.status!=="uploaded"?<Pressable disabled={uploading===String(request.id)} onPress={()=>upload(request)} style={styles.upload}>{uploading===String(request.id)?<ActivityIndicator color="#fff"/>:<Text style={styles.uploadText}>Upload</Text>}</Pressable>:<Text style={styles.done}>✓</Text>}</View>):<View style={styles.empty}><Text style={styles.emptyTitle}>No documents requested</Text><Text style={styles.emptyText}>If the employer requests a document, it will appear here.</Text></View>}<Text style={styles.section}>Application history</Text>{(data?.history||[]).length?(data.history.map((entry,index)=><View key={index} style={styles.history}><Text style={styles.historyStatus}>{entry.status}</Text><Text style={styles.historyNote}>{entry.note||"Status updated"}</Text></View>)):<Text style={styles.historyNote}>Your application was submitted successfully.</Text>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},header:{padding:20,paddingBottom:18,backgroundColor:"#fff"},back:{color:"#2563eb",fontWeight:"800"},heading:{fontSize:25,fontWeight:"900",color:"#172033",marginTop:18},title:{fontSize:16,color:"#172033",fontWeight:"900",marginTop:12},company:{color:"#2563eb",fontSize:13,fontWeight:"700",marginTop:3},content:{padding:16,paddingBottom:40},section:{fontSize:17,fontWeight:"900",color:"#172033",marginTop:13,marginBottom:10},status:{alignSelf:"flex-start",paddingHorizontal:12,paddingVertical:8,borderRadius:16,backgroundColor:"#dcfce7"},statusText:{color:"#15803d",fontWeight:"900",fontSize:12},request:{backgroundColor:"#fff",borderRadius:16,padding:15,marginBottom:10,flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:"#e5eaf2"},requestTitle:{color:"#172033",fontWeight:"900",fontSize:14},note:{color:"#64748b",fontSize:12,lineHeight:17,marginTop:4},requestStatus:{color:"#e11d48",fontSize:11,fontWeight:"800",marginTop:8},upload:{backgroundColor:"#2563eb",borderRadius:10,paddingVertical:10,paddingHorizontal:12,marginLeft:10,minWidth:70,alignItems:"center"},uploadText:{color:"#fff",fontWeight:"900",fontSize:12},done:{fontSize:24,color:"#16a34a",fontWeight:"900",marginLeft:8},empty:{backgroundColor:"#fff",padding:17,borderRadius:15},emptyTitle:{color:"#172033",fontWeight:"900"},emptyText:{color:"#64748b",fontSize:12,lineHeight:18,marginTop:5},history:{borderLeftWidth:3,borderLeftColor:"#2563eb",paddingLeft:11,paddingVertical:6,marginBottom:5},historyStatus:{color:"#172033",fontSize:13,fontWeight:"900"},historyNote:{color:"#64748b",fontSize:12,marginTop:3},center:{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:"#f4f7fb"}});
