import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import * as DocumentPicker from "expo-document-picker";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";

export default function ApplyJob() {
  const { id, title, company } = useLocalSearchParams();
  const [resume, setResume] = useState(null); const [submitting, setSubmitting] = useState(false);
  const pickResume = async () => { const result = await DocumentPicker.getDocumentAsync({ type:"application/pdf", copyToCacheDirectory:true }); if (!result.canceled) setResume(result.assets[0]); };
  const submit = async () => { if (!resume) return Alert.alert("Resume required", "Choose your resume as a PDF before applying."); setSubmitting(true); try { const token = await AsyncStorage.getItem("token"); const form = new FormData(); form.append("jobId", String(id)); form.append("resume", { uri:resume.uri, name:resume.name || "resume.pdf", type:resume.mimeType || "application/pdf" }); const response = await api.post("/apply", form, { headers:{ Authorization:`Bearer ${token}`, "Content-Type":"multipart/form-data" } }); Alert.alert("Application submitted", "You can track updates from your Applications tab.", [{ text:"View applications", onPress:() => router.replace("/applications") }]); } catch (error) { Alert.alert("Could not submit application", error?.response?.data?.error || "Please try again."); } finally { setSubmitting(false); } };
  return <SafeAreaView style={s.screen}><View style={s.content}><Pressable onPress={() => router.back()}><Text style={s.back}>← Back to job</Text></Pressable><Text style={s.eyebrow}>APPLICATION</Text><Text style={s.heading}>Apply with confidence</Text><View style={s.job}><Text style={s.jobTitle}>{title || "Job opening"}</Text><Text style={s.company}>{company || "MarketLence Jobs"}</Text></View><Text style={s.copy}>Upload a PDF resume. Your application will be sent directly to the employer and available in your application tracker.</Text><Pressable onPress={pickResume} style={s.upload}><Text style={s.uploadIcon}>↑</Text><View style={{flex:1}}><Text style={s.uploadTitle}>{resume ? "Resume selected" : "Choose PDF resume"}</Text><Text numberOfLines={1} style={s.uploadSub}>{resume?.name || "PDF files only"}</Text></View><Text style={s.change}>{resume ? "Change" : "Choose"}</Text></Pressable><Pressable onPress={submit} disabled={submitting} style={[s.submit, submitting && s.disabled]}>{submitting ? <ActivityIndicator color="#fff" /> : <Text style={s.submitText}>Submit application</Text>}</Pressable><Text style={s.note}>By submitting, you confirm that your resume may be shared with the employer for this role.</Text></View></SafeAreaView>;
}
const s = StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},content:{padding:21},back:{color:"#2563eb",fontWeight:"900"},eyebrow:{color:"#2563eb",fontSize:11,fontWeight:"900",letterSpacing:1,marginTop:33},heading:{color:"#172033",fontSize:30,fontWeight:"900",marginTop:8},job:{backgroundColor:"#fff",borderRadius:17,padding:16,marginTop:25,borderWidth:1,borderColor:"#e5eaf2"},jobTitle:{color:"#172033",fontWeight:"900",fontSize:17},company:{color:"#2563eb",fontWeight:"800",fontSize:13,marginTop:5},copy:{color:"#64748b",lineHeight:20,marginTop:20,fontSize:13},upload:{backgroundColor:"#fff",borderRadius:16,borderWidth:1,borderColor:"#cbdcf7",padding:15,marginTop:21,flexDirection:"row",alignItems:"center"},uploadIcon:{height:39,width:39,borderRadius:12,backgroundColor:"#dbeafe",color:"#2563eb",fontSize:23,fontWeight:"900",textAlign:"center",paddingTop:5,marginRight:11},uploadTitle:{color:"#172033",fontWeight:"900",fontSize:14},uploadSub:{color:"#64748b",fontSize:11,marginTop:4},change:{color:"#2563eb",fontWeight:"900",fontSize:12},submit:{backgroundColor:"#2563eb",borderRadius:13,padding:16,alignItems:"center",marginTop:23},disabled:{opacity:.65},submitText:{color:"#fff",fontWeight:"900",fontSize:15},note:{color:"#94a3b8",fontSize:11,lineHeight:17,textAlign:"center",marginTop:14}});
