import { Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import * as WebBrowser from "expo-web-browser";

const openTool = (path) => WebBrowser.openBrowserAsync(`https://jobs.marketlence.com${path}`, { presentationStyle: WebBrowser.WebBrowserPresentationStyle.PAGE_SHEET });

export default function CareerTools() {
  return <SafeAreaView style={styles.screen}><View style={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.eyebrow}>CAREER TOOLS</Text><Text style={styles.heading}>Build your next move</Text><Text style={styles.subheading}>Create a polished resume or convert a document without leaving MarketLence Jobs.</Text><Pressable onPress={() => openTool("/resume-builder")} style={[styles.card, styles.resume]}><Text style={styles.icon}>✦</Text><View style={styles.cardText}><Text style={styles.cardTitle}>Resume Builder</Text><Text style={styles.cardSub}>Choose a template, enter details, import an existing resume, and build it from your phone.</Text><Text style={styles.action}>Build a resume →</Text></View></Pressable><Pressable onPress={() => openTool("/docs-converter")} style={[styles.card, styles.docs]}><Text style={styles.icon}>⇄</Text><View style={styles.cardText}><Text style={styles.cardTitle}>Docs Converter</Text><Text style={styles.cardSub}>Convert pictures, PDF, Word, Excel, and text documents between supported formats.</Text><Text style={styles.action}>Convert a document →</Text></View></Pressable><View style={styles.note}><Text style={styles.noteText}>Your work opens securely inside the app and uses the same MarketLence Jobs tools available on the website.</Text></View></View></SafeAreaView>;
}
const styles = StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},content:{padding:21},back:{color:"#2563eb",fontWeight:"800"},eyebrow:{color:"#2563eb",fontSize:11,fontWeight:"900",letterSpacing:1,marginTop:31},heading:{fontSize:30,fontWeight:"900",color:"#172033",marginTop:8},subheading:{color:"#64748b",lineHeight:21,marginTop:8},card:{marginTop:23,borderRadius:21,padding:19,flexDirection:"row"},resume:{backgroundColor:"#eaf2ff",borderWidth:1,borderColor:"#c9dcff"},docs:{backgroundColor:"#f4edff",borderWidth:1,borderColor:"#ddd0ff"},icon:{fontSize:26,color:"#2563eb",width:45},cardText:{flex:1},cardTitle:{fontSize:18,fontWeight:"900",color:"#172033"},cardSub:{color:"#526176",fontSize:13,lineHeight:19,marginTop:6},action:{color:"#2563eb",fontSize:13,fontWeight:"900",marginTop:14},note:{backgroundColor:"#fff",borderRadius:13,padding:14,marginTop:22},noteText:{color:"#64748b",fontSize:12,lineHeight:18}});
