import AsyncStorage from "@react-native-async-storage/async-storage";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import BottomNav from "../components/BottomNav";
import api from "../services/api";

export default function Dashboard() {
  const [stats, setStats] = useState({ saved: 0, applications: 0 }); const [name, setName] = useState("there");
  const load = async () => { const values=Object.fromEntries(await AsyncStorage.multiGet(["userId","username","token"])); setName(values.username || "there"); if (!values.token || !values.userId) return; const [saved, applications] = await Promise.allSettled([api.get(`/saved-jobs/${values.userId}`), api.get("/applications")]); setStats({ saved: saved.status === "fulfilled" ? saved.value.data.length : 0, applications: applications.status === "fulfilled" ? applications.value.data.length : 0 }); };
  useFocusEffect(useCallback(() => { load(); }, []));
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>← Back</Text></TouchableOpacity><Text style={styles.title}>Career dashboard</Text><Text style={styles.sub}>Hello, {name}. Keep your job search moving.</Text><View style={styles.stats}><Stat value={stats.applications} label="Applications" /><Stat value={stats.saved} label="Saved jobs" /></View><Text style={styles.section}>Quick actions</Text><Tile title="Browse new jobs" subtitle="Find roles that match your goals." onPress={() => router.replace("/home")} /><Tile title="Review applications" subtitle="See updates and next steps." onPress={() => router.replace("/applications")} /><Tile title="Open resume builder" subtitle="Build, edit, and download a resume." onPress={() => router.replace("/profile")} /></ScrollView><BottomNav /></SafeAreaView>;
}
function Stat({value,label}) { return <View style={styles.stat}><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>; } function Tile({title,subtitle,onPress}) { return <TouchableOpacity style={styles.tile} onPress={onPress}><Text style={styles.tileTitle}>{title}</Text><Text style={styles.tileSub}>{subtitle}</Text><Text style={styles.open}>Open →</Text></TouchableOpacity>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F8FF"},content:{padding:20,paddingBottom:32},back:{color:"#2563EB",fontWeight:"800",marginBottom:18},title:{fontSize:27,fontWeight:"800",color:"#111827"},sub:{color:"#64748B",marginTop:6},stats:{flexDirection:"row",gap:12,marginTop:22},stat:{flex:1,backgroundColor:"#1D4ED8",borderRadius:18,padding:19},value:{fontSize:27,fontWeight:"900",color:"#FFF"},label:{color:"#DBEAFE",marginTop:4,fontWeight:"700",fontSize:13},section:{fontSize:17,fontWeight:"800",color:"#111827",marginTop:27,marginBottom:10},tile:{backgroundColor:"#FFF",borderRadius:17,padding:18,marginBottom:12,borderWidth:1,borderColor:"#E5EAF3"},tileTitle:{color:"#111827",fontSize:16,fontWeight:"800"},tileSub:{color:"#64748B",fontSize:13,marginTop:5},open:{color:"#2563EB",fontWeight:"800",marginTop:13,fontSize:13}});
