import AsyncStorage from "@react-native-async-storage/async-storage";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, Linking, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import api from "../services/api";

export default function EmployerDashboard() {
  const [data, setData] = useState(null); const [name, setName] = useState("Employer"); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const values = Object.fromEntries(await AsyncStorage.multiGet(["token","role","username"])); if (!values.token || values.role !== "employer") { router.replace("/employer-login"); return; } setName(values.username || "Employer"); try { setData((await api.get("/employer/dashboard")).data); } catch (error) { Alert.alert("Employer dashboard", error?.response?.data?.error || "We could not load your dashboard."); } finally { setLoading(false); } };
  useFocusEffect(useCallback(() => { load(); }, []));
  const openWeb = async (path) => { const url=`https://jobs.marketlence.com${path}`; if (await Linking.canOpenURL(url)) Linking.openURL(url); };
  const logout = async () => { await AsyncStorage.multiRemove(["token","role","userId","username","email"]); router.replace("/home"); };
  if (loading) return <SafeAreaView style={styles.center}><ActivityIndicator color="#7C3AED" size="large"/></SafeAreaView>;
  const stats=data?.stats || {};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><View><Text style={styles.eyebrow}>EMPLOYER WORKSPACE</Text><Text style={styles.title}>Hello, {name}</Text></View><TouchableOpacity onPress={logout}><Text style={styles.logout}>Log out</Text></TouchableOpacity></View><TouchableOpacity style={styles.post} onPress={() => openWeb("/employer/post-job")}><Text style={styles.postText}>＋ Post a job</Text></TouchableOpacity><View style={styles.stats}><Stat value={stats.live_jobs || 0} label="Live jobs"/><Stat value={stats.pending_jobs || 0} label="In review"/><Stat value={stats.total_apply_clicks || 0} label="Apply clicks"/></View><Text style={styles.section}>Your jobs</Text>{(data?.jobs || []).length ? data.jobs.map((job) => <View key={job.id} style={styles.job}><View style={styles.jobCopy}><Text style={styles.jobTitle}>{job.title}</Text><Text style={styles.jobMeta}>{job.location} · {job.employer_status}</Text></View>{job.is_featured ? <Text style={styles.featured}>FEATURED</Text> : null}</View>) : <View style={styles.empty}><Text style={styles.emptyTitle}>No job postings yet</Text><Text style={styles.emptyText}>Create your first job on the secure employer portal.</Text></View>}<Text style={styles.section}>Hiring tools</Text><Tool title="Applications" detail="Review candidates, messages, and documents." onPress={() => openWeb("/employer/dashboard")} /><Tool title="HR services" detail="Manage employees, leave, and documents." onPress={() => openWeb("/employer/hr")} /><Tool title="Featured job plans" detail="Promote approved roles with Razorpay." onPress={() => openWeb("/employer/dashboard")} /></ScrollView></SafeAreaView>;
}
function Stat({value,label}){return <View style={styles.stat}><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>} function Tool({title,detail,onPress}) {return <TouchableOpacity style={styles.tool} onPress={onPress}><View style={{flex:1}}><Text style={styles.toolTitle}>{title}</Text><Text style={styles.toolDetail}>{detail}</Text></View><Text style={styles.arrow}>›</Text></TouchableOpacity>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F8F7FF"},center:{flex:1,justifyContent:"center",alignItems:"center"},content:{padding:20,paddingBottom:35},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},eyebrow:{color:"#7C3AED",fontWeight:"900",fontSize:11,letterSpacing:1},title:{fontSize:25,fontWeight:"900",color:"#111827",marginTop:5},logout:{color:"#6D28D9",fontWeight:"800",padding:5},post:{backgroundColor:"#7C3AED",borderRadius:15,alignItems:"center",padding:17,marginTop:22},postText:{color:"#FFF",fontWeight:"900",fontSize:16},stats:{flexDirection:"row",gap:9,marginTop:15},stat:{flex:1,backgroundColor:"#FFF",borderRadius:15,padding:14,borderWidth:1,borderColor:"#E9E1FF"},value:{fontSize:22,fontWeight:"900",color:"#4C1D95"},label:{color:"#6B7280",fontSize:11,fontWeight:"700",marginTop:4},section:{color:"#111827",fontWeight:"900",fontSize:17,marginTop:27,marginBottom:10},job:{backgroundColor:"#FFF",borderRadius:16,padding:16,marginBottom:10,borderWidth:1,borderColor:"#E9E1FF",flexDirection:"row",alignItems:"flex-start",gap:8},jobCopy:{flex:1},jobTitle:{color:"#111827",fontSize:16,fontWeight:"800"},jobMeta:{color:"#64748B",fontSize:12,marginTop:6},featured:{color:"#6D28D9",fontWeight:"900",fontSize:10,backgroundColor:"#F3E8FF",padding:6,borderRadius:8},empty:{backgroundColor:"#FFF",borderRadius:16,padding:18,borderWidth:1,borderColor:"#E9E1FF"},emptyTitle:{color:"#111827",fontWeight:"800"},emptyText:{color:"#64748B",fontSize:13,marginTop:5,lineHeight:19},tool:{backgroundColor:"#FFF",borderRadius:16,padding:16,marginBottom:10,borderWidth:1,borderColor:"#E9E1FF",flexDirection:"row",alignItems:"center"},toolTitle:{fontWeight:"800",color:"#111827"},toolDetail:{color:"#64748B",fontSize:12,marginTop:4,lineHeight:18},arrow:{fontSize:28,color:"#7C3AED",marginLeft:10}});
