import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";

const num = (value) => Number(value || 0);

export default function EmployerDashboard() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const [token, role] = await AsyncStorage.multiGet(["token", "role"]); if (!token[1] || role[1] !== "employer") { router.replace("/employer-login"); return; } const response = await api.get("/employer/dashboard", { headers: { Authorization: `Bearer ${token[1]}` } }); setData(response.data); setError(""); } catch (err) { setError(err?.response?.data?.error || "Could not load your employer dashboard."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const logout = () => Alert.alert("Log out", "Log out of your employer account?", [{ text:"Cancel", style:"cancel" }, { text:"Log out", style:"destructive", onPress: async () => { await AsyncStorage.multiRemove(["token","role","userId","email","username"]); router.replace("/home"); }}]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563eb"/></View>;
  const stats = data?.stats || {}; const jobs = Array.isArray(data?.jobs) ? data.jobs : [];
  return <SafeAreaView style={styles.screen}><View style={styles.header}><View><Text style={styles.eyebrow}>EMPLOYER DASHBOARD</Text><Text style={styles.heading}>Your hiring hub</Text></View><Pressable onPress={logout}><Text style={styles.logout}>Log out</Text></Pressable></View><FlatList data={jobs} keyExtractor={(item) => String(item.id)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor="#2563eb"/>} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.stats}><Stat value={num(stats.live_jobs)} label="Live jobs"/><Stat value={num(stats.pending_jobs)} label="In review"/><Stat value={num(stats.total_apply_clicks)} label="Apply clicks"/></View><View style={styles.actions}><Pressable onPress={() => router.push("/employer-post-job")} style={styles.primary}><Text style={styles.primaryText}>＋ Post a job</Text></Pressable><Pressable onPress={() => router.push("/employer-applications")} style={styles.secondary}><Text style={styles.secondaryText}>View candidates</Text></Pressable></View><Text style={styles.section}>Your posted jobs</Text>{error ? <Text style={styles.error}>{error}</Text> : null}</>} renderItem={({item}) => <View style={styles.job}><View style={styles.jobTop}><View style={{flex:1}}><Text style={styles.title}>{item.title}</Text><Text style={styles.location}>⌖ {item.location || "Location not specified"}</Text></View>{item.is_featured ? <Text style={styles.featured}>FEATURED</Text> : null}</View><View style={styles.jobBottom}><Text style={[styles.status, item.employer_status === "Live" && styles.live]}>{item.employer_status || "Pending Review"}</Text><Text style={styles.views}>{num(item.views_count)} views · {num(item.apply_clicks)} clicks</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No jobs posted yet</Text><Text style={styles.emptyText}>Create your first opening to start finding candidates.</Text></View>}/></SafeAreaView>;
}
function Stat({value,label}) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},header:{padding:20,paddingBottom:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"#fff"},eyebrow:{color:"#2563eb",fontWeight:"900",fontSize:10,letterSpacing:1},heading:{color:"#172033",fontWeight:"900",fontSize:25,marginTop:4},logout:{color:"#e11d48",fontWeight:"800",fontSize:12},list:{padding:16,paddingBottom:35},stats:{flexDirection:"row",gap:9},stat:{flex:1,backgroundColor:"#fff",borderRadius:16,padding:14,borderWidth:1,borderColor:"#e5eaf2"},statValue:{color:"#2563eb",fontSize:24,fontWeight:"900"},statLabel:{color:"#64748b",fontSize:10,fontWeight:"800",marginTop:5},actions:{flexDirection:"row",gap:10,marginTop:18},primary:{flex:1,alignItems:"center",backgroundColor:"#2563eb",borderRadius:12,padding:13},primaryText:{color:"#fff",fontWeight:"900",fontSize:13},secondary:{alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#2563eb",borderRadius:12,paddingHorizontal:13},secondaryText:{color:"#2563eb",fontWeight:"900",fontSize:12},section:{fontSize:19,fontWeight:"900",color:"#172033",marginTop:27,marginBottom:12},job:{backgroundColor:"#fff",borderRadius:16,padding:16,marginBottom:11,borderWidth:1,borderColor:"#e5eaf2"},jobTop:{flexDirection:"row"},title:{fontSize:16,fontWeight:"900",color:"#172033",paddingRight:10},location:{fontSize:12,color:"#64748b",marginTop:6},featured:{alignSelf:"flex-start",color:"#78350f",backgroundColor:"#fef3c7",padding:6,borderRadius:9,fontSize:9,fontWeight:"900"},jobBottom:{flexDirection:"row",marginTop:14,alignItems:"center",justifyContent:"space-between"},status:{backgroundColor:"#fef3c7",color:"#92400e",borderRadius:14,paddingVertical:6,paddingHorizontal:9,fontSize:10,fontWeight:"900"},live:{backgroundColor:"#dcfce7",color:"#15803d"},views:{fontSize:11,color:"#64748b",fontWeight:"700"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#f4f7fb"},empty:{alignItems:"center",paddingTop:45},emptyTitle:{color:"#172033",fontSize:17,fontWeight:"900"},emptyText:{color:"#64748b",marginTop:6,textAlign:"center"},error:{color:"#e11d48",fontSize:12,marginBottom:10}});
