import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";

const stages = ["Applied", "Shortlisted", "Interview", "Selected", "Rejected"];

export default function EmployerApplicationWorkspace() {
  const { id } = useLocalSearchParams();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState(""); const [requestName, setRequestName] = useState(""); const [note, setNote] = useState("");
  const load = useCallback(async () => { try { const token = await AsyncStorage.getItem("token"); const response = await api.get(`/applications/${id}/workspace`, { headers:{ Authorization:`Bearer ${token}` } }); setData(response.data); } catch (error) { Alert.alert("Could not load candidate", error?.response?.data?.error || "Please try again."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  const send = async () => { if (!message.trim()) return; try { const token = await AsyncStorage.getItem("token"); await api.post(`/applications/${id}/messages`, { body:message.trim() }, { headers:{ Authorization:`Bearer ${token}` } }); setMessage(""); load(); } catch (error) { Alert.alert("Message failed", error?.response?.data?.error || "Please try again."); } };
  const requestDocument = async () => { if (!requestName.trim()) return Alert.alert("Document name required", "For example: Updated resume or ID proof."); try { const token = await AsyncStorage.getItem("token"); await api.post(`/employer/applications/${id}/documents/request`, { documentName:requestName.trim(), note:note.trim() }, { headers:{ Authorization:`Bearer ${token}` } }); setRequestName(""); setNote(""); load(); } catch (error) { Alert.alert("Request failed", error?.response?.data?.error || "Please try again."); } };
  const setStage = () => Alert.alert("Update application stage", "Choose the current stage.", stages.map((status) => ({ text:status, onPress:async () => { try { const token = await AsyncStorage.getItem("token"); await api.patch(`/employer/applications/${id}/status`, { status }, { headers:{ Authorization:`Bearer ${token}` } }); load(); } catch (error) { Alert.alert("Update failed", error?.response?.data?.error || "Please try again."); } } })).concat([{ text:"Cancel", style:"cancel" }]));
  if (loading) return <View style={s.center}><ActivityIndicator size="large" color="#2563eb" /></View>;
  const app = data?.application || {}; const docs = data?.documents || []; const messages = data?.messages || [];
  return <SafeAreaView style={s.screen}><View style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>← Candidates</Text></Pressable><Text style={s.heading}>{app.name || "Candidate"}</Text><Text style={s.sub}>{app.title || "Job application"}</Text><Pressable onPress={setStage} style={s.stage}><Text style={s.stageText}>{app.status || "Applied"} · Update</Text></Pressable></View><ScrollView contentContainerStyle={s.content}><Text style={s.section}>Request a document</Text><View style={s.panel}><TextInput value={requestName} onChangeText={setRequestName} placeholder="Document name, e.g. Updated resume" placeholderTextColor="#94a3b8" style={s.input}/><TextInput value={note} onChangeText={setNote} placeholder="Optional note for the candidate" placeholderTextColor="#94a3b8" style={[s.input,{marginTop:8}]} multiline/><Pressable onPress={requestDocument} style={s.primary}><Text style={s.primaryText}>Request document</Text></Pressable></View><Text style={s.section}>Documents</Text>{docs.length ? docs.map((doc) => <View key={doc.id} style={s.card}><Text style={s.bold}>{doc.document_name}</Text><Text style={s.small}>{doc.status === "uploaded" ? "Uploaded by candidate" : "Awaiting candidate"}</Text></View>) : <Text style={s.small}>No documents requested yet.</Text>}<Text style={s.section}>Conversation</Text>{messages.length ? messages.map((item) => <View key={item.id} style={[s.message,item.sender_role === "employer" && s.mine]}><Text style={s.role}>{item.sender_role === "employer" ? "You" : "Candidate"}</Text><Text style={s.messageText}>{item.body}</Text></View>) : <Text style={s.small}>Start the conversation with this candidate.</Text>}<View style={s.composer}><TextInput value={message} onChangeText={setMessage} placeholder="Write a message" placeholderTextColor="#94a3b8" style={s.composerInput} multiline/><Pressable onPress={send} style={s.send}><Text style={s.primaryText}>Send</Text></Pressable></View></ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},header:{padding:20,backgroundColor:"#fff"},back:{color:"#2563eb",fontWeight:"900"},heading:{fontSize:25,fontWeight:"900",color:"#172033",marginTop:17},sub:{color:"#64748b",fontWeight:"700",marginTop:5},stage:{alignSelf:"flex-start",marginTop:12,paddingHorizontal:10,paddingVertical:8,borderRadius:10,backgroundColor:"#dcfce7"},stageText:{fontWeight:"900",color:"#15803d",fontSize:12},content:{padding:16,paddingBottom:42},section:{fontWeight:"900",fontSize:17,color:"#172033",marginTop:17,marginBottom:9},panel:{backgroundColor:"#fff",borderRadius:15,padding:13},input:{borderWidth:1,borderColor:"#d8e0eb",borderRadius:11,padding:11,color:"#172033",minHeight:44},primary:{backgroundColor:"#2563eb",borderRadius:11,padding:12,alignItems:"center",marginTop:10},primaryText:{color:"#fff",fontWeight:"900",fontSize:12},card:{backgroundColor:"#fff",borderRadius:13,padding:13,marginBottom:8},bold:{fontWeight:"900",color:"#172033"},small:{color:"#64748b",fontSize:12,lineHeight:18,marginTop:4},message:{backgroundColor:"#fff",borderRadius:13,padding:12,marginBottom:8},mine:{backgroundColor:"#dbeafe"},role:{color:"#2563eb",fontSize:10,fontWeight:"900"},messageText:{color:"#172033",lineHeight:19,marginTop:4},composer:{marginTop:9,flexDirection:"row",alignItems:"flex-end",gap:8},composerInput:{flex:1,minHeight:46,maxHeight:110,backgroundColor:"#fff",borderWidth:1,borderColor:"#d8e0eb",borderRadius:12,padding:11,color:"#172033"},send:{backgroundColor:"#2563eb",borderRadius:11,padding:13,minWidth:58,alignItems:"center"},center:{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:"#f4f7fb"}});
