import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";

const statuses = ["Applied", "Shortlisted", "Interview", "Selected", "Rejected"];

export default function EmployerApplications() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const token = await AsyncStorage.getItem("token"); const response = await api.get("/employer/applications", { headers:{ Authorization:`Bearer ${token}` } }); setItems(Array.isArray(response.data) ? response.data : []); } catch (error) { Alert.alert("Could not load candidates", error?.response?.data?.error || "Please try again."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const update = (application) => Alert.alert("Update candidate", "Choose the current application stage.", statuses.map((status) => ({ text: status, onPress: async () => { try { const token = await AsyncStorage.getItem("token"); await api.patch(`/employer/applications/${application.id}/status`, { status }, { headers:{ Authorization:`Bearer ${token}` } }); load(); } catch (error) { Alert.alert("Update failed", error?.response?.data?.error || "Please try again."); } }})).concat([{ text:"Cancel", style:"cancel" }]));
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563eb" /></View>;
  return <SafeAreaView style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.heading}>Candidates</Text><Text style={styles.subheading}>Applications managed through your jobs.</Text></View><FlatList data={items} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor="#2563eb"/>} renderItem={({item}) => <Pressable onPress={() => update(item)} style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{String(item.name || "C").charAt(0).toUpperCase()}</Text></View><View style={styles.info}><Text style={styles.name}>{item.name || "Candidate"}</Text><Text style={styles.job}>{item.title || "Job application"}</Text><Text style={styles.email}>{item.email || "Email not shared"}</Text><Text style={styles.status}>{item.status || "Applied"}</Text></View><Text style={styles.arrow}>›</Text></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No managed applications yet</Text><Text style={styles.emptyText}>Candidates will appear here when they apply through a job managed on MarketLence Jobs.</Text></View>}/></SafeAreaView>;
}
const styles = StyleSheet.create({screen:{flex:1,backgroundColor:"#f4f7fb"},header:{padding:20,paddingBottom:9},back:{color:"#2563eb",fontWeight:"800"},heading:{fontSize:28,fontWeight:"900",color:"#172033",marginTop:17},subheading:{color:"#64748b",fontSize:13,marginTop:5},list:{padding:16,paddingTop:8,paddingBottom:32},card:{backgroundColor:"#fff",borderRadius:17,padding:15,flexDirection:"row",alignItems:"center",marginBottom:11,borderWidth:1,borderColor:"#e5eaf2"},avatar:{width:45,height:45,borderRadius:15,backgroundColor:"#e0ecff",justifyContent:"center",alignItems:"center"},avatarText:{color:"#2563eb",fontWeight:"900",fontSize:18},info:{marginLeft:12,flex:1},name:{fontSize:15,fontWeight:"900",color:"#172033"},job:{color:"#2563eb",fontSize:12,fontWeight:"700",marginTop:3},email:{color:"#64748b",fontSize:11,marginTop:4},status:{alignSelf:"flex-start",color:"#15803d",backgroundColor:"#dcfce7",paddingHorizontal:8,paddingVertical:4,borderRadius:10,marginTop:8,fontSize:10,fontWeight:"900"},arrow:{fontSize:28,color:"#2563eb"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#f4f7fb"},empty:{alignItems:"center",paddingTop:70,paddingHorizontal:28},emptyTitle:{fontSize:18,fontWeight:"900",color:"#172033",textAlign:"center"},emptyText:{color:"#64748b",lineHeight:20,marginTop:8,textAlign:"center"}});
