import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import api from "../services/api";

export default function EmployerLogin() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false);
  const signIn = async () => { setLoading(true); try { const { data } = await api.post("/employers/login", { email, password }); await AsyncStorage.multiSet([["token", data.token], ["role", "employer"], ["userId", String(data.userId)], ["username", data.username || "Employer"], ["email", data.email]]); router.replace("/employer-dashboard"); } catch (error) { Alert.alert("Employer login", error?.response?.data?.error || "Please check your email and password."); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><View style={styles.content}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>← Back</Text></TouchableOpacity><Text style={styles.eyebrow}>MARKETLENCE FOR EMPLOYERS</Text><Text style={styles.title}>Manage your hiring from anywhere.</Text><Text style={styles.sub}>Sign in to post roles, review applications, and manage your team.</Text><TextInput style={styles.input} placeholder="Work email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><TextInput style={styles.input} placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><TouchableOpacity style={[styles.primary,loading&&styles.disabled]} disabled={loading} onPress={signIn}><Text style={styles.primaryText}>{loading ? "Signing in..." : "Employer sign in"}</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={() => Alert.alert("Create employer account", "Open jobs.marketlence.com/employer/signup in your browser to verify your business email and create an employer account.")}><Text style={styles.secondaryText}>Create employer account</Text></TouchableOpacity></View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F8FF"},content:{padding:25,justifyContent:"center",flex:1},back:{color:"#2563EB",fontWeight:"800",position:"absolute",top:25,left:25},eyebrow:{color:"#7C3AED",fontSize:12,fontWeight:"900",letterSpacing:1.2},title:{fontSize:30,fontWeight:"900",color:"#111827",lineHeight:37,marginTop:10},sub:{color:"#64748B",lineHeight:21,marginTop:10,marginBottom:28},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#D7E0F2",borderRadius:13,padding:15,marginBottom:13,color:"#111827"},primary:{backgroundColor:"#7C3AED",borderRadius:13,padding:16,alignItems:"center",marginTop:5},primaryText:{color:"#FFF",fontWeight:"800",fontSize:16},disabled:{opacity:.6},secondary:{borderWidth:1.5,borderColor:"#7C3AED",borderRadius:13,padding:15,alignItems:"center",marginTop:12},secondaryText:{color:"#6D28D9",fontWeight:"800"}});
