import AsyncStorage from "@react-native-async-storage/async-storage";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { Alert, Linking, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import BottomNav from "../components/BottomNav";

export default function Profile() {
  const [account, setAccount] = useState(null);
  const load = async () => { const values = Object.fromEntries(await AsyncStorage.multiGet(["token", "username", "email"])); setAccount(values.token ? values : null); };
  useFocusEffect(useCallback(() => { load(); }, []));
  const logout = async () => { await AsyncStorage.multiRemove(["token", "role", "userId", "email", "username"]); setAccount(null); router.replace("/home"); };
  const open = async (path) => { const url = `https://jobs.marketlence.com${path}`; const supported = await Linking.canOpenURL(url); if (supported) Linking.openURL(url); else Alert.alert("Unable to open link"); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Profile</Text>{account ? <><View style={styles.person}><View style={styles.avatar}><Text style={styles.avatarText}>{(account.username || "M").charAt(0).toUpperCase()}</Text></View><View><Text style={styles.name}>{account.username || "Marketlence member"}</Text><Text style={styles.email}>{account.email}</Text></View></View><Text style={styles.section}>Career tools</Text><Action title="Build or update your resume" detail="Templates, voice input, document import and downloads." onPress={() => open("/resume-builder")} /><Action title="Job alerts" detail="Choose job notifications from the website." onPress={() => open("/jobs")} /><Action title="Candidate dashboard" detail="Manage your career information and applications." onPress={() => router.push("/dashboard")} /><Text style={styles.section}>Account</Text><Action title="Work as a freelancer" detail="Create a freelancer profile on Marketlence." onPress={() => open("/freelance")} /><Action title="For employers" detail="Post and manage company jobs." onPress={() => router.push("/employer-login")} /><TouchableOpacity style={styles.logout} onPress={logout}><Text style={styles.logoutText}>Log out</Text></TouchableOpacity></> : <View style={styles.signin}><Text style={styles.signinTitle}>Your career, in one place.</Text><Text style={styles.signinText}>Log in to save jobs, apply, receive updates, and build your profile.</Text><TouchableOpacity style={styles.primary} onPress={() => router.push("/login")}><Text style={styles.primaryText}>Log in</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={() => router.push("/signup")}><Text style={styles.secondaryText}>Create account</Text></TouchableOpacity></View>}</ScrollView><BottomNav /></SafeAreaView>;
}
function Action({title,detail,onPress}) { return <TouchableOpacity style={styles.action} onPress={onPress}><View style={styles.actionCopy}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.actionDetail}>{detail}</Text></View><Text style={styles.chevron}>›</Text></TouchableOpacity>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F8FF"},content:{padding:20,paddingBottom:32},title:{fontSize:27,fontWeight:"800",color:"#111827",marginBottom:20},person:{backgroundColor:"#1D4ED8",borderRadius:20,padding:20,flexDirection:"row",alignItems:"center",gap:14},avatar:{height:53,width:53,borderRadius:18,backgroundColor:"#FFF",alignItems:"center",justifyContent:"center"},avatarText:{fontWeight:"900",fontSize:22,color:"#1D4ED8"},name:{fontSize:18,fontWeight:"800",color:"#FFF"},email:{color:"#DBEAFE",marginTop:4,fontSize:13},section:{fontWeight:"800",fontSize:16,color:"#111827",marginTop:25,marginBottom:10},action:{backgroundColor:"#FFF",borderRadius:16,padding:16,marginBottom:10,borderWidth:1,borderColor:"#E5EAF3",flexDirection:"row",alignItems:"center"},actionCopy:{flex:1},actionTitle:{fontWeight:"800",fontSize:15,color:"#111827"},actionDetail:{color:"#64748B",fontSize:12,lineHeight:18,marginTop:4},chevron:{fontSize:28,color:"#2563EB",marginLeft:10},logout:{borderWidth:1.5,borderColor:"#DC2626",borderRadius:13,alignItems:"center",padding:14,marginTop:18},logoutText:{fontWeight:"800",color:"#DC2626"},signin:{backgroundColor:"#FFF",borderRadius:20,padding:22,borderWidth:1,borderColor:"#E5EAF3"},signinTitle:{fontWeight:"800",fontSize:21,color:"#111827"},signinText:{color:"#64748B",marginTop:8,lineHeight:21},primary:{backgroundColor:"#2563EB",borderRadius:13,alignItems:"center",padding:15,marginTop:22},primaryText:{color:"#FFF",fontWeight:"800"},secondary:{borderColor:"#2563EB",borderWidth:1.5,borderRadius:13,alignItems:"center",padding:14,marginTop:10},secondaryText:{color:"#2563EB",fontWeight:"800"}});
