import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";
import BottomNav from "../components/BottomNav";

export default function Profile() {
  const [account, setAccount] = useState(null); const [stats, setStats] = useState(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const [token, userId, username, email] = await AsyncStorage.multiGet(["token", "userId", "username", "email"]); const values = Object.fromEntries([["token", token], ["userId", userId], ["username", username], ["email", email]]); if (!values.token || !values.userId) { setAccount(null); setLoading(false); return; } setAccount(values); try { const response = await api.get(`/dashboard-stats/${values.userId}`, { headers: { Authorization: `Bearer ${values.token}` } }); setStats(response.data); } catch {} finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const logout = () => Alert.alert("Log out", "Do you want to log out of MarketLence Jobs?", [{ text: "Cancel", style: "cancel" }, { text: "Log out", style: "destructive", onPress: async () => { await AsyncStorage.multiRemove(["token", "role", "userId", "username", "email", "profilePic"]); router.replace("/home"); } }]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563eb"/></View>;
  if (!account) return <SafeAreaView style={styles.screen}><View style={styles.center}><Text style={styles.emptyTitle}>Your career space is waiting</Text><Text style={styles.emptyText}>Log in to save jobs and track your applications.</Text><Pressable onPress={() => router.replace("/login")} style={styles.primary}><Text style={styles.primaryText}>Log in</Text></Pressable><Pressable onPress={() => router.push("/signup")}><Text style={styles.link}>Create an account</Text></Pressable></View><BottomNav active="profile" /></SafeAreaView>;
  const initials = String(account.username || "M").trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  return <SafeAreaView style={styles.screen}><View style={styles.content}><Pressable onPress={() => router.replace("/home")}><Text style={styles.back}>← Home</Text></Pressable><Text style={styles.heading}>My profile</Text><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><View style={styles.profileInfo}><Text style={styles.name}>{account.username || "MarketLence candidate"}</Text><Text style={styles.email}>{account.email}</Text><Text style={styles.member}>Candidate account</Text></View></View><Text style={styles.section}>Your activity</Text><View style={styles.stats}><View style={styles.statCard}><Text style={styles.statNumber}>{stats?.saved || 0}</Text><Text style={styles.statLabel}>Saved jobs</Text></View><View style={styles.statCard}><Text style={styles.statNumber}>{stats?.applied || 0}</Text><Text style={styles.statLabel}>Applications</Text></View></View><Pressable onPress={() => router.push("/saved-jobs")} style={styles.row}><View><Text style={styles.rowTitle}>Saved jobs</Text><Text style={styles.rowSub}>Open your shortlisted opportunities</Text></View><Text style={styles.arrow}>›</Text></Pressable><Pressable onPress={() => router.push("/applications")} style={styles.row}><View><Text style={styles.rowTitle}>Applications</Text><Text style={styles.rowSub}>Track your application progress</Text></View><Text style={styles.arrow}>›</Text></Pressable><Pressable onPress={() => router.push("/job-alerts")} style={styles.row}><View><Text style={styles.rowTitle}>Job alerts</Text><Text style={styles.rowSub}>Choose your matching-job email updates</Text></View><Text style={styles.arrow}>›</Text></Pressable><Pressable onPress={logout} style={styles.logout}><Text style={styles.logoutText}>Log out</Text></Pressable></View><BottomNav active="profile" /></SafeAreaView>;
}
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:"#f4f7fb"},content:{flex:1,padding:20},center:{flex:1,alignItems:"center",justifyContent:"center",padding:30,backgroundColor:"#f4f7fb"},back:{color:"#2563eb",fontWeight:"800"},heading:{color:"#172033",fontSize:29,fontWeight:"900",marginTop:20},profileCard:{marginTop:22,backgroundColor:"#1d4ed8",borderRadius:22,padding:19,flexDirection:"row",alignItems:"center"},avatar:{height:58,width:58,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:"#dbeafe"},avatarText:{fontSize:20,fontWeight:"900",color:"#1d4ed8"},profileInfo:{marginLeft:14,flex:1},name:{color:"#fff",fontWeight:"900",fontSize:18},email:{color:"#dbeafe",marginTop:4,fontSize:13},member:{color:"#bfdbfe",marginTop:8,fontSize:11,fontWeight:"800"},section:{fontWeight:"900",fontSize:18,color:"#172033",marginTop:28,marginBottom:12},stats:{flexDirection:"row",gap:12},statCard:{flex:1,backgroundColor:"#fff",borderRadius:16,padding:16},statNumber:{color:"#2563eb",fontWeight:"900",fontSize:28},statLabel:{color:"#64748b",fontWeight:"700",fontSize:12,marginTop:4},row:{backgroundColor:"#fff",borderRadius:15,padding:16,marginTop:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},rowTitle:{color:"#172033",fontWeight:"900",fontSize:15},rowSub:{color:"#64748b",fontSize:12,marginTop:4},arrow:{fontSize:29,color:"#2563eb",fontWeight:"400"},logout:{borderWidth:1,borderColor:"#fecdd3",borderRadius:13,padding:14,alignItems:"center",marginTop:28,backgroundColor:"#fff"},logoutText:{color:"#e11d48",fontWeight:"900"},emptyTitle:{fontSize:22,color:"#172033",fontWeight:"900",textAlign:"center"},emptyText:{color:"#64748b",textAlign:"center",lineHeight:20,marginTop:8},primary:{marginTop:23,backgroundColor:"#2563eb",borderRadius:12,paddingHorizontal:22,paddingVertical:13},primaryText:{color:"#fff",fontWeight:"900"},link:{color:"#2563eb",fontWeight:"800",marginTop:17} });
