import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, SafeAreaView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import api from "../services/api";
import BottomNav from "../components/BottomNav";

export default function SavedJobs() {
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [signedOut, setSignedOut] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); const userId = await AsyncStorage.getItem("userId"); if (!userId) { setSignedOut(true); setLoading(false); setRefreshing(false); return; } try { const result = await api.get(`/saved-jobs/${userId}`); setJobs(Array.isArray(result.data) ? result.data : []); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const remove = async (job) => { const userId = await AsyncStorage.getItem("userId"); try { await api.delete("/unsave-job", { data: { user_id: userId, job_id: job.job_id, external_job_id: job.external_job_id } }); setJobs((current) => current.filter((item) => item.id !== job.id)); } catch { alert("Could not remove this saved job."); } };
  const card = ({ item }) => <View style={styles.card}><Pressable onPress={() => item.job_id ? router.push({ pathname: "/job/[id]", params: { id: String(item.job_id) } }) : null}><Text style={styles.title}>{item.title}</Text><Text style={styles.company}>{item.company}</Text><Text style={styles.location}>⌖ {item.location || "Location not specified"}</Text></Pressable><View style={styles.actions}><Pressable onPress={() => item.job_id ? router.push({ pathname: "/job/[id]", params: { id: String(item.job_id) } }) : null} style={styles.view}><Text style={styles.viewText}>View job</Text></Pressable><Pressable onPress={() => remove(item)} style={styles.remove}><Text style={styles.removeText}>Remove</Text></Pressable></View></View>;
  return <SafeAreaView style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.replace("/home")}><Text style={styles.back}>← Home</Text></Pressable><Text style={styles.heading}>Saved Jobs</Text></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#2563eb"/></View> : signedOut ? <View style={styles.center}><Text style={styles.emptyTitle}>Log in to see saved jobs</Text><Pressable onPress={() => router.push("/login")} style={styles.login}><Text style={styles.loginText}>Log in</Text></Pressable></View> : <FlatList data={jobs} renderItem={card} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor="#2563eb"/>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No saved jobs yet</Text><Text style={styles.emptyText}>Save jobs you want to revisit here.</Text><Pressable onPress={() => router.replace("/home")} style={styles.login}><Text style={styles.loginText}>Browse jobs</Text></Pressable></View>}/> }<BottomNav active="saved" /></SafeAreaView>;
}
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:"#f4f7fb"},header:{paddingHorizontal:20,paddingTop:14,paddingBottom:18,backgroundColor:"#fff"},back:{color:"#2563eb",fontWeight:"800"},heading:{fontSize:27,fontWeight:"900",color:"#172033",marginTop:18},list:{padding:16,paddingBottom:32},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e5eaf2",borderRadius:18,padding:16,marginBottom:12},title:{fontSize:17,fontWeight:"900",color:"#172033"},company:{color:"#2563eb",fontWeight:"700",marginTop:6},location:{color:"#64748b",marginTop:6,fontSize:13},actions:{flexDirection:"row",gap:10,marginTop:16},view:{flex:1,alignItems:"center",padding:11,borderRadius:10,backgroundColor:"#2563eb"},viewText:{color:"#fff",fontWeight:"800"},remove:{paddingHorizontal:15,alignItems:"center",justifyContent:"center",borderRadius:10,borderWidth:1,borderColor:"#fda4af"},removeText:{color:"#e11d48",fontWeight:"800"},center:{flex:1,alignItems:"center",justifyContent:"center",padding:25},empty:{paddingTop:80,alignItems:"center",paddingHorizontal:25},emptyTitle:{fontSize:18,fontWeight:"900",color:"#334155",textAlign:"center"},emptyText:{color:"#94a3b8",marginTop:7,textAlign:"center"},login:{marginTop:20,backgroundColor:"#2563eb",paddingHorizontal:19,paddingVertical:12,borderRadius:11},loginText:{color:"#fff",fontWeight:"900"} });
