import AsyncStorage from "@react-native-async-storage/async-storage";
import { router, useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, FlatList, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import BottomNav from "../components/BottomNav";
import api from "../services/api";

export default function SavedJobs() {
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [loggedIn, setLoggedIn] = useState(false);
  const load = async () => { setLoading(true); const userId = await AsyncStorage.getItem("userId"); setLoggedIn(Boolean(userId)); if (!userId) { setJobs([]); setLoading(false); return; } try { setJobs((await api.get(`/saved-jobs/${userId}`)).data || []); } catch { Alert.alert("Saved jobs", "We could not load your saved jobs."); } finally { setLoading(false); } };
  useFocusEffect(useCallback(() => { load(); }, []));
  const remove = async (job) => { const userId = await AsyncStorage.getItem("userId"); try { await api.delete("/unsave-job", { data: { user_id: Number(userId), job_id: job.job_id, external_job_id: job.external_job_id } }); setJobs((items) => items.filter((item) => item.id !== job.id)); } catch { Alert.alert("Could not remove job", "Please try again."); } };
  return <SafeAreaView style={styles.safe}><View style={styles.heading}><Text style={styles.title}>Saved jobs</Text><Text style={styles.sub}>Your shortlist, ready when you are.</Text></View>{loading ? <ActivityIndicator style={styles.loader} color="#2563EB" size="large" /> : !loggedIn ? <Empty text="Log in to keep jobs in your shortlist." button="Log in" onPress={() => router.push("/login")} /> : <FlatList data={jobs} keyExtractor={(job) => String(job.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Empty text="You have not saved a job yet." button="Explore jobs" onPress={() => router.replace("/home")} />} renderItem={({ item }) => <View style={styles.card}><Text style={styles.job}>{item.title || "Job"}</Text><Text style={styles.company}>{item.company || "Company"}</Text><Text style={styles.location}>{item.location || "Location not specified"}</Text><TouchableOpacity onPress={() => remove(item)}><Text style={styles.remove}>Remove</Text></TouchableOpacity></View>} /> }<BottomNav /></SafeAreaView>;
}
function Empty({ text, button, onPress }) { return <View style={styles.empty}><Text style={styles.emptyText}>{text}</Text><TouchableOpacity style={styles.primary} onPress={onPress}><Text style={styles.primaryText}>{button}</Text></TouchableOpacity></View>; }
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:"#F5F8FF"}, heading:{padding:20,paddingBottom:8},title:{fontSize:27,fontWeight:"800",color:"#111827"},sub:{marginTop:5,color:"#64748B"},loader:{flex:1},list:{padding:20,paddingTop:12,paddingBottom:30,flexGrow:1},card:{backgroundColor:"#FFF",borderRadius:17,padding:18,marginBottom:12,borderWidth:1,borderColor:"#E5EAF3"},job:{fontSize:17,fontWeight:"800",color:"#111827"},company:{color:"#475569",marginTop:5,fontWeight:"600"},location:{color:"#64748B",marginTop:8,fontSize:13},remove:{color:"#DC2626",fontWeight:"800",marginTop:15},empty:{flex:1,alignItems:"center",justifyContent:"center",padding:30},emptyText:{color:"#475569",fontSize:16,textAlign:"center",lineHeight:23},primary:{backgroundColor:"#2563EB",borderRadius:12,paddingHorizontal:20,paddingVertical:13,marginTop:18},primaryText:{color:"#FFF",fontWeight:"800"} });
