import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import api from "../services/api";

export default function Signup() {
  const [username, setUsername] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [otp, setOtp] = useState(""); const [otpSent, setOtpSent] = useState(false); const [alerts, setAlerts] = useState(true); const [busy, setBusy] = useState(false);
  const sendOtp = async () => { if (!username.trim() || !email.trim() || password.length < 8) return Alert.alert("Complete your details", "Enter your name, a valid email, and a password with at least 8 characters."); setBusy(true); try { await api.post("/send-email-otp", { email: email.trim().toLowerCase() }); setOtpSent(true); Alert.alert("Verification code sent", "Check your email for the OTP."); } catch (error) { Alert.alert("Could not send code", error.response?.data?.error || "Please try again."); } finally { setBusy(false); } };
  const verifyAndCreate = async () => { if (otp.trim().length < 4) return Alert.alert("Enter the code", "Please enter the OTP sent to your email."); setBusy(true); try { await api.post("/verify-email-otp", { username: username.trim(), email: email.trim().toLowerCase(), password, otp: otp.trim(), isAdmin: false, jobAlertsEnabled: alerts }); Alert.alert("Account created", "You can now log in and start applying for jobs.", [{ text: "Continue", onPress: () => router.replace("/login") }]); } catch (error) { Alert.alert("Could not create account", error.response?.data?.error || "Please check the OTP and try again."); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.brand}>MarketLence Jobs</Text><Text style={styles.title}>Create your candidate account</Text><Text style={styles.subtitle}>Save jobs, manage applications and get relevant job alerts.</Text><View style={styles.card}><Text style={styles.label}>Full name</Text><TextInput value={username} onChangeText={setUsername} editable={!otpSent && !busy} placeholder="Your name" style={styles.input}/><Text style={styles.label}>Email address</Text><TextInput value={email} onChangeText={setEmail} editable={!otpSent && !busy} autoCapitalize="none" keyboardType="email-address" placeholder="you@email.com" style={styles.input}/><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} editable={!otpSent && !busy} secureTextEntry placeholder="At least 8 characters" style={styles.input}/><View style={styles.alertRow}><View style={styles.alertText}><Text style={styles.alertTitle}>Email job alerts</Text><Text style={styles.alertSub}>Get relevant opportunities in your inbox.</Text></View><Switch value={alerts} onValueChange={setAlerts} disabled={otpSent || busy} trackColor={{ false: "#cbd5e1", true: "#93c5fd" }} thumbColor={alerts ? "#2563eb" : "#f8fafc"}/></View>{otpSent && <><Text style={styles.label}>Verification code</Text><TextInput value={otp} onChangeText={setOtp} keyboardType="number-pad" maxLength={6} placeholder="Enter OTP from your email" style={styles.input}/><Pressable disabled={busy} onPress={sendOtp}><Text style={styles.resend}>Resend verification code</Text></Pressable></>}<Pressable onPress={otpSent ? verifyAndCreate : sendOtp} disabled={busy} style={[styles.action, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff"/> : <Text style={styles.actionText}>{otpSent ? "Verify & create account" : "Send verification code"}</Text>}</Pressable><Pressable onPress={() => router.replace("/login")} disabled={busy}><Text style={styles.login}>Already have an account? Log in</Text></Pressable></View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:"#f4f7fb"},content:{padding:20,paddingBottom:44},back:{color:"#2563eb",fontWeight:"800"},brand:{color:"#2563eb",fontWeight:"900",fontSize:15,marginTop:34},title:{color:"#172033",fontSize:29,lineHeight:35,fontWeight:"900",marginTop:8},subtitle:{color:"#64748b",fontSize:14,lineHeight:21,marginTop:9},card:{backgroundColor:"#fff",borderRadius:22,marginTop:26,padding:19,shadowColor:"#0f172a",shadowOpacity:.07,shadowRadius:12,elevation:3},label:{color:"#334155",fontWeight:"800",fontSize:13,marginTop:14,marginBottom:7},input:{borderWidth:1,borderColor:"#dbe3ee",borderRadius:12,paddingHorizontal:13,paddingVertical:13,color:"#172033",fontSize:14},alertRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:22,padding:13,borderRadius:13,backgroundColor:"#eff6ff"},alertText:{flex:1,paddingRight:10},alertTitle:{color:"#1e3a8a",fontWeight:"800",fontSize:13},alertSub:{color:"#526176",fontSize:12,marginTop:3},resend:{color:"#2563eb",fontWeight:"800",fontSize:12,marginTop:10},action:{alignItems:"center",justifyContent:"center",minHeight:51,borderRadius:13,backgroundColor:"#2563eb",marginTop:25},disabled:{opacity:.65},actionText:{color:"#fff",fontWeight:"900",fontSize:15},login:{textAlign:"center",color:"#2563eb",fontWeight:"800",marginTop:19,fontSize:13} });
